---
fullname: Freer Equational Reasoning for Distributed and Probabilistic Systems
shortname: FreerDPS
organization: FreerDPS
community: false
action: true
coqdoc: false

synopsis:
  TODO

description: |-
  TODO

publications:
- TODO

authors:
- name: Hugo Forraz
  initial: true

maintainers:
- name: Hugo Forraz
  initial: true

opam-file-maintainer: Hugo Forraz

license:
  fullname: MIT License
  identifier: MIT
  file: LICENSE

supported_rocq_versions:
  text: 9.0
  opam: '{ (= "9.0") | (= "dev") }'

tested_rocq_opam_versions:
- version: '2.5.0-rocq-prover-9.0'
  repo: 'mathcomp/mathcomp'

dependencies:
- opam:
    name: rocq-mathcomp-ssreflect
    version: '{>= "2.5.0"}'
  description: |-
    [MathComp](https://math-comp.github.io)
- opam:
    name: rocq-mathcomp-analysis
    version: '{>= "1.16.0"}'
  description: |-
    [MathComp Analysis](https://github.com/math-comp/analysis)
- opam:
    name: coq-mathcomp-algebra-tactics
    version: '{>= "1.2.7"}'
  description: |-
    [MathComp Algebra Tactics](https://github.com/math-comp/algebra-tactics)
- opam:
    name: rocq-monae
    version: '{= "0.9.2"}'
  description: |-
    Monae
---