---
fullname: Freer Equational Reasoning for Distributed and Probabilistic Systems
shortname: FreerDPS
organization: FreerDPS
community: false
action: true
coqdoc: false

synopsis:
  TODO

description: |-
  This work started as a rewrite/extension of [FreeSpec Core](https://github.com/lthms/FreeSpec) using [monae](https://github.com/affeldt-aist/monae) / ssreflect.

  This work has been accepted for presentation to [COMPAS26](https://2026.compas-conference.fr/) (no paper available online).

publications:
- TODO

authors:
- name: Hugo Forraz
  initial: true

maintainers:
- name: Hugo Forraz
  initial: true

opam-file-maintainer: Hugo Forraz

license:
  fullname: MIT License
  identifier: MIT
  file: LICENSE

supported_rocq_versions:
  text: 9.0
  opam: '{ (= "9.2.0") | (= "dev") }'

tested_rocq_opam_versions:
- version: '2.6.0-rocq-prover-9.2'
  repo: 'mathcomp/mathcomp'

dependencies:
- opam:
    name: rocq-mathcomp-ssreflect
    version: '{>= "2.6.0"}'
  description: |-
    [MathComp](https://math-comp.github.io)
- opam:
    name: rocq-mathcomp-analysis
    version: '{>= "1.18.0"}'
  description: |-
    [MathComp Analysis](https://github.com/math-comp/analysis)
- opam:
    name: rocq-monae
    version: '{= "0.9.3"}'
  description: |-
    Monae
---